name: Python application test

on: [push, pull_request]

jobs:
  test_math:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run math tests
      run: python test_math.py

  test_web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@v1.0.1

    - name: Setup Edge Driver
      uses: microsoft/edge-docker@v1.0.0

    - name: Run web tests
      run: python test_web.py