name: Selenium Grid tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GRID_HUB_PORT: 4444
  GRID_BROWSER_FF_PORT: 5555
  GRID_BROWSER_CHROME_PORT: 5556

services:
  selenium-hub:
    image: selenium/hub:4.8.0-20230123
    ports:
      - "$GRID_HUB_PORT:4444"
    command: ["-shm-size", "1g"]
  firefox:
    image: selenium/node-firefox:4.8.0-20230123
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
      - "$GRID_BROWSER_FF_PORT:5555"
    command: ["-shm-size", "1g"]
  chrome:
    image: selenium/node-chrome:4.8.0-20230123
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
      - "$GRID_BROWSER_CHROME_PORT:5556"
    command: ["-shm-size", "1g"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Selenium Grid
      uses: docker://selenium/hub:4.8.0-20230123
      with:
        args: -role hub
      env:
        GRID_HUB_PORT: 4444

    - name: Start Selenium node (Firefox)
      uses: docker://selenium/node-firefox:4.8.0-20230123
      with:
        args: -role node -hub http://localhost:4444/grid/register
      env:
        GRID_BROWSER_FF_PORT: 5555

    - name: Start Selenium node (Chrome)
      uses: docker://selenium/node-chrome:4.8.0-20230123
      with:
        args: -role node -hub http://localhost:4444/grid/register
      env:
        GRID_BROWSER_CHROME_PORT: 5556

    - name: Run tests
      uses: python:3.9
      env:
        SELENIUM_GRID_URL: "http://localhost:4444/wd/"
      run: pytest tests/
