name: Selenium Grid tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  scrape:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:4.0
        ports:
          - 4444:4444
      chrome:
        image: selenium/node-chrome:4.0
        env:
          HUB_HOST: selenium-hub
          HUB_PORT: 4444
        depends_on:
          selenium-hub: {condition: service_started}
      chrome2:
        image: selenium/node-chrome:4.0
        env:
          HUB_HOST: selenium-hub
          HUB_PORT: 4444
        depends_on:
          selenium-hub: {condition: service_started}
      chrome3:
        image: selenium/node-chrome:4.0
        env:
          HUB_HOST: selenium-hub
          HUB_PORT: 4444
        depends_on:
          selenium-hub: {condition: service_started}
      firefox:
        image: selenium/node-firefox:4.0
        env:
          HUB_HOST: selenium-hub
          HUB_PORT: 4444
        depends_on:
          selenium-hub: {condition: service_started}

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installing all necessary packages
        run: pip install -r requirements.txt

      - name: GUI tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: python your_test_script.py